/**
 * Generated by @proofkit/typegen package
 * https://proofkit.proof.sh/docs/typegen
 * DO NOT EDIT THIS FILE DIRECTLY. Changes may be overwritten
 */
import { DataApi } from "@proofkit/fmdapi";
import { WebViewerAdapter } from "@proofkit/webviewer/adapter";
import { ZAccounts } from "../Accounts";

export const client = DataApi({
  adapter: new WebViewerAdapter({ scriptName: "ExecuteDataApi" }),
  layout: "Accounts",
  schema: { fieldData: ZAccounts },
});
